language: generic

sudo: required
services:
  - docker

install:
  - docker build -t $DOCKER_HUB_PASS/aws-hello-world .

script:
  - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCHER_HUB_LOGIN}" --password-stdin

deploy:
  provider: script
  script: docker push "$DOCKER_HUB_LOGIN"/aws-hello-world
  on:
    branch: main