language: generic

sudo: required
services:
  - docker

install:
  - docker build -t alexandrbolkunets/aws-hello-world .

script:
  - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCHER_HUB_LOGIN" --password-stdin

deploy:
  provider: script
  script: docker push alexandrbolkunets/aws-hello-world
  on:
    branch: main
